name = "trelleborg-innotrans"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "USERS"
id = "REPLACE_WITH_USERS_KV_ID"

[[kv_namespaces]]
binding = "LEADS"
id = "REPLACE_WITH_LEADS_KV_ID"
